FROM openjdk:8-jdk-alpine
LABEL maintainer="ebelitoa@nttdata.com"
ADD kafka-consumer-0.0.1-SNAPSHOT.jar kafka-consumer-0.0.1-SNAPSHOT.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar","/kafka-consumer-0.0.1-SNAPSHOT.jar"]